FROM centos:7

RUN yum -y --setopt=tsflags=nodocs update && \
    yum -y --setopt=tsflags=nodocs install \
        cmake \
        curl \
        gcc \
        gcc-c++ \
        git \
        glew \
        glew-devel \
        libXcursor \
        libXcursor-devel \
        libXi \
        libXi-devel \
        libXinerama \
        libXinerama-devel \
        libXrandr \
        libXrandr-devel \
        make \
        python3 \
        python3-devel \
        python-devel \
        zlib \
        zlib-devel \
        && \
    yum clean all

RUN python3.6 -m pip install PySide2 jinja2 PyOpenGL

# test stuff
RUN yum -y install glx-utils xeyes

# qt stuff
RUN yum -y install qt5-qtbase libxkbcommon-x11

WORKDIR /opt/USD

ENV PATH=/opt/USD-inst/bin:${PATH}
ENV PYTHONPATH=/opt/USD-inst/lib/python:${PYTHONPATH}

CMD [ "/bin/bash" ]

